server:
  port: 8082
  servlet:
    context-path: /gen

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    #oracle配置
#    driverClassName: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@192.168.10.10:1521:helowin
#    username: admin
#    password: 123456
    #SQLServer配置
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://192.168.10.10:1433;DatabaseName=nsdm_db
#    username: admin
#    password: 123456
    #PostgreSQL配置
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://192.168.10.10:5432/nsdm_db
#    username: postgres
#    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/

mybatis-plus:
   mapper-locations: classpath*:mapper/*Dao.xml
   configuration:
    map-underscore-to-camel-case: true

#mybatis:
#  config-location: classpath:mapper/*.xml 配置文件
#  mapper-locations: classpath*:mapper/*Dao.xml xml文件
      
#pagehelper:
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
